# -*- coding: utf-8 -*-
"""生成 data/team_names.json：英文队名(含变体) -> 中文名。"""
import json
import re
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent

# 完整映射：英文名(含变体) -> 中文名
T = {
    # 英超
    "Arsenal FC": "阿森纳", "Arsenal": "阿森纳",
    "Aston Villa FC": "阿斯顿维拉", "Aston Villa": "阿斯顿维拉",
    "Chelsea FC": "切尔西", "Chelsea": "切尔西",
    "Everton FC": "埃弗顿", "Everton": "埃弗顿",
    "Fulham FC": "富勒姆", "Fulham": "富勒姆",
    "Liverpool FC": "利物浦", "Liverpool": "利物浦",
    "Manchester City FC": "曼城", "Manchester City": "曼城", "Man City": "曼城",
    "Manchester United FC": "曼联", "Manchester United": "曼联", "Man United": "曼联",
    "Newcastle United FC": "纽卡斯尔联", "Newcastle United": "纽卡斯尔联", "Newcastle": "纽卡斯尔联",
    "Nottingham Forest FC": "诺丁汉森林", "Nottingham Forest": "诺丁汉森林", "Nottingham": "诺丁汉森林",
    "Tottenham Hotspur FC": "热刺", "Tottenham Hotspur": "热刺", "Tottenham": "热刺",
    "West Ham United FC": "西汉姆联", "West Ham United": "西汉姆联",
    "Wolverhampton Wanderers FC": "狼队", "Wolves": "狼队",
    "Crystal Palace FC": "水晶宫", "Crystal Palace": "水晶宫",
    "Brighton & Hove Albion FC": "布莱顿", "Brighton and Hove Albion": "布莱顿", "Brighton Hove": "布莱顿", "Brighton": "布莱顿",
    "Brentford FC": "布伦特福德", "Brentford": "布伦特福德",
    "AFC Bournemouth": "伯恩茅斯", "Bournemouth": "伯恩茅斯",
    "Southampton FC": "南安普顿", "Southampton": "南安普顿",
    "Ipswich Town FC": "伊普斯维奇", "Ipswich Town": "伊普斯维奇", "Ipswich": "伊普斯维奇",
    "Leicester City FC": "莱斯特城", "Leicester": "莱斯特城",
    "Leeds United FC": "利兹联", "Leeds United": "利兹联", "Leeds": "利兹联",
    "Coventry City FC": "考文垂", "Coventry City": "考文垂", "Coventry": "考文垂",
    "Hull City AFC": "赫尔城", "Hull City": "赫尔城", "Hull": "赫尔城",
    "Sunderland AFC": "桑德兰", "Sunderland": "桑德兰",
    "Burnley FC": "伯恩利", "Burnley": "伯恩利",
    "Middlesbrough FC": "米德尔斯堡", "Middlesbrough": "米德尔斯堡",
    "Sheffield United FC": "谢菲尔德联", "Sheffield United": "谢菲尔德联",
    "Norwich City FC": "诺维奇", "Norwich City": "诺维奇",
    "Stoke City FC": "斯托克城", "Stoke City": "斯托克城",
    "Bristol City FC": "布里斯托尔城", "Bristol City": "布里斯托尔城",
    "Swansea City AFC": "斯旺西", "Swansea City": "斯旺西",
    "Cardiff City FC": "加的夫城", "Cardiff City": "加的夫城",
    "Blackburn Rovers FC": "布莱克本", "Blackburn Rovers": "布莱克本",
    "Millwall FC": "米尔沃尔", "Millwall": "米尔沃尔",
    "Preston North End FC": "普雷斯顿", "Preston North End": "普雷斯顿",
    "Derby County FC": "德比郡", "Derby County": "德比郡",
    "Portsmouth FC": "朴茨茅斯", "Portsmouth": "朴茨茅斯",
    "Bolton Wanderers FC": "博尔顿", "Bolton Wanderers": "博尔顿",
    "Charlton Athletic FC": "查尔顿", "Charlton Athletic": "查尔顿",
    "Birmingham City FC": "伯明翰", "Birmingham City": "伯明翰",
    "Lincoln City FC": "林肯城", "Lincoln City": "林肯城",
    "Queens Park Rangers FC": "女王公园巡游者", "Queens Park Rangers": "女王公园巡游者",
    # 西甲
    "Real Madrid CF": "皇家马德里", "Real Madrid": "皇家马德里",
    "FC Barcelona": "巴塞罗那", "Barcelona": "巴塞罗那", "Barça": "巴塞罗那",
    "Atlético de Madrid": "马德里竞技", "Atletico Madrid": "马德里竞技", "Club Atlético de Madrid": "马德里竞技", "Atlético Madrid": "马德里竞技", "Atleti": "马德里竞技",
    "Real Betis Balompié": "皇家贝蒂斯", "Real Betis": "皇家贝蒂斯",
    "Real Sociedad": "皇家社会", "Real Sociedad de Fútbol": "皇家社会",
    "Athletic Club": "毕尔巴鄂竞技", "Athletic Bilbao": "毕尔巴鄂竞技", "Athletic": "毕尔巴鄂竞技",
    "Sevilla FC": "塞维利亚", "Sevilla": "塞维利亚",
    "Villarreal CF": "比利亚雷亚尔", "Villarreal": "比利亚雷亚尔",
    "Valencia CF": "瓦伦西亚", "Valencia": "瓦伦西亚",
    "RC Celta de Vigo": "塞尔塔", "Celta Vigo": "塞尔塔", "Celta": "塞尔塔",
    "Deportivo Alavés": "阿拉维斯", "Alavés": "阿拉维斯", "Alaves": "阿拉维斯",
    "CA Osasuna": "奥萨苏纳", "Osasuna": "奥萨苏纳",
    "Getafe CF": "赫塔菲", "Getafe": "赫塔菲",
    "RCD Mallorca": "马略卡", "Mallorca": "马略卡",
    "Girona FC": "赫罗纳", "Girona": "赫罗纳",
    "Rayo Vallecano": "巴列卡诺", "Rayo Vallecano de Madrid": "巴列卡诺",
    "UD Las Palmas": "拉斯帕尔马斯",
    "CD Leganés": "莱加内斯", "Leganes": "莱加内斯",
    "Real Valladolid CF": "巴拉多利德", "Valladolid": "巴拉多利德",
    "RCD Espanyol de Barcelona": "西班牙人", "Espanyol": "西班牙人",
    "Levante UD": "莱万特", "Levante": "莱万特",
    "Elche CF": "埃尔切", "Elche": "埃尔切",
    "Málaga CF": "马拉加", "Málaga": "马拉加", "Malaga": "马拉加",
    "Deportivo La Coruña": "拉科鲁尼亚", "Deportivo": "拉科鲁尼亚", "RC Deportivo La Coruña": "拉科鲁尼亚",
    "Real Racing Club de Santander": "桑坦德竞技", "Santander": "桑坦德竞技",
    # 意甲
    "Juventus FC": "尤文图斯", "Juventus": "尤文图斯",
    "AC Milan": "AC米兰", "Milan": "AC米兰",
    "FC Internazionale Milano": "国际米兰", "Inter": "国际米兰", "Inter Milan": "国际米兰",
    "SSC Napoli": "那不勒斯", "Napoli": "那不勒斯",
    "AS Roma": "罗马", "Roma": "罗马",
    "SS Lazio": "拉齐奥", "Lazio": "拉齐奥",
    "ACF Fiorentina": "佛罗伦萨", "Fiorentina": "佛罗伦萨",
    "Atalanta BC": "亚特兰大", "Atalanta": "亚特兰大",
    "FC Bologna": "博洛尼亚", "Bologna": "博洛尼亚", "Bologna FC 1909": "博洛尼亚",
    "Torino FC": "都灵", "Torino": "都灵",
    "Genoa CFC": "热那亚", "Genoa": "热那亚",
    "Udinese Calcio": "乌迪内斯", "Udinese": "乌迪内斯",
    "Como 1907": "科莫", "Como": "科莫",
    "Empoli FC": "恩波利",
    "SSC Monza 1912": "蒙扎", "AC Monza": "蒙扎", "Monza": "蒙扎",
    "Cagliari Calcio": "卡利亚里", "Cagliari": "卡利亚里",
    "US Lecce": "莱切", "Lecce": "莱切",
    "Hellas Verona": "维罗纳",
    "Parma Calcio 1913": "帕尔马", "Parma": "帕尔马",
    "US Sassuolo Calcio": "萨索洛", "Sassuolo": "萨索洛",
    "Frosinone Calcio": "弗罗西诺内", "Frosinone": "弗罗西诺内",
    "Venezia FC": "威尼斯", "Venezia": "威尼斯",
    # 德甲
    "FC Bayern München": "拜仁慕尼黑", "Bayern Munich": "拜仁慕尼黑", "Bayern": "拜仁慕尼黑",
    "Borussia Dortmund": "多特蒙德", "Dortmund": "多特蒙德",
    "RB Leipzig": "莱比锡红牛", "Leipzig": "莱比锡红牛",
    "Bayer 04 Leverkusen": "勒沃库森", "Bayer Leverkusen": "勒沃库森", "Leverkusen": "勒沃库森",
    "VfB Stuttgart": "斯图加特", "Stuttgart": "斯图加特",
    "Eintracht Frankfurt": "法兰克福", "Frankfurt": "法兰克福",
    "VfL Wolfsburg": "沃尔夫斯堡",
    "Borussia Mönchengladbach": "门兴格拉德巴赫", "Borussia Monchengladbach": "门兴格拉德巴赫", "M'gladbach": "门兴格拉德巴赫",
    "SC Freiburg": "弗赖堡", "Freiburg": "弗赖堡",
    "1. FC Union Berlin": "柏林联合", "Union Berlin": "柏林联合",
    "FC Augsburg": "奥格斯堡", "Augsburg": "奥格斯堡",
    "1. FSV Mainz 05": "美因茨", "FSV Mainz 05": "美因茨", "Mainz": "美因茨",
    "TSG 1899 Hoffenheim": "霍芬海姆", "TSG Hoffenheim": "霍芬海姆", "Hoffenheim": "霍芬海姆",
    "VfL Bochum": "波鸿",
    "SV Werder Bremen": "不莱梅", "Bremen": "不莱梅", "Werder Bremen": "不莱梅",
    "FC St. Pauli": "圣保利",
    "FC Schalke 04": "沙尔克04", "Schalke": "沙尔克04",
    "Hertha BSC": "柏林赫塔",
    "1. FC Heidenheim 1846": "海登海姆",
    "Holstein Kiel": "基尔",
    "1. FC Köln": "科隆", "Köln": "科隆", "FC Koln": "科隆",
    "Hamburger SV": "汉堡", "HSV": "汉堡",
    "SC Paderborn 07": "帕德博恩", "SC Paderborn": "帕德博恩", "Paderborn": "帕德博恩",
    "SV 07 Elversberg": "埃弗斯堡", "Elversberg": "埃弗斯堡",
    # 法甲
    "Paris Saint-Germain FC": "巴黎圣日耳曼", "Paris Saint Germain": "巴黎圣日耳曼", "PSG": "巴黎圣日耳曼",
    "Olympique de Marseille": "马赛", "Marseille": "马赛",
    "Olympique Lyonnais": "里昂", "Olympique Lyon": "里昂", "Lyon": "里昂",
    "AS Monaco FC": "摩纳哥", "AS Monaco": "摩纳哥", "Monaco": "摩纳哥",
    "Stade Rennais FC 1901": "雷恩", "Stade Rennais": "雷恩", "Rennes": "雷恩",
    "OGC Nice": "尼斯", "Nice": "尼斯",
    "LOSC Lille": "里尔", "Lille": "里尔", "Lille OSC": "里尔",
    "RC Lens": "朗斯", "Racing Club de Lens": "朗斯", "Lens": "朗斯",
    "Montpellier Hérault SC": "蒙彼利埃",
    "FC Nantes": "南特",
    "RC Strasbourg Alsace": "斯特拉斯堡", "Strasbourg": "斯特拉斯堡",
    "Stade de Reims": "兰斯",
    "Toulouse FC": "图卢兹", "Toulouse": "图卢兹",
    "Stade Brestois 29": "布雷斯特", "Brest": "布雷斯特",
    "AJ Auxerre": "欧塞尔", "Auxerre": "欧塞尔",
    "Angers SCO": "昂热", "Angers": "昂热",
    "Le Havre AC": "勒阿弗尔", "Le Havre": "勒阿弗尔",
    "Paris FC": "巴黎FC",
    "ES Troyes AC": "特鲁瓦", "Troyes": "特鲁瓦",
    "FC Lorient": "洛里昂", "Lorient": "洛里昂",
    "Le Mans FC": "勒芒", "Le Mans": "勒芒",
    # 荷甲
    "Ajax": "阿贾克斯",
    "PSV Eindhoven": "埃因霍温",
    "Feyenoord": "费耶诺德",
    "AZ Alkmaar": "阿尔克马尔",
    "FC Twente Enschede": "特温特", "Twente": "特温特",
    "FC Utrecht": "乌得勒支", "Utrecht": "乌得勒支",
    "Sparta Rotterdam": "鹿特丹斯巴达",
    "Heerenveen": "海伦芬",
    "Groningen": "格罗宁根",
    "Fortuna Sittard": "福图纳锡塔德",
    "Excelsior": "精英队",
    "FC Zwolle": "兹沃勒", "Zwolle": "兹沃勒",
    "NEC Nijmegen": "奈梅亨",
    "ADO Den Haag": "海牙",
    "SC Telstar": "特尔斯达",
    "Go Ahead Eagles": "前进之鹰",
    # 葡超
    "Benfica": "本菲卡",
    "FC Porto": "波尔图",
    "Sporting Lisbon": "葡萄牙体育",
    "Braga": "布拉加",
    "Rio Ave FC": "里奥阿维",
    "Gil Vicente": "吉尔维森特",
    "Moreirense FC": "莫雷伦斯",
    "Arouca": "阿鲁卡",
    "Casa Pia": "卡萨皮亚",
    "CS Maritimo": "马里迪莫",
    "Santa Clara": "圣克拉拉",
    "Académico de Viseu": "维塞乌学院",
    "CF Estrela": "埃斯特雷拉",
    "Alverca": "阿尔韦卡",
    "Nacional": "国民队",
    # 土超
    "Galatasaray": "加拉塔萨雷",
    "Fenerbahce": "费内巴切",
    "Besiktas JK": "贝西克塔斯",
    "Trabzonspor": "特拉布宗体育",
    "Basaksehir": "巴萨克赛尔",
    "Alanyaspor": "阿拉尼亚体育",
    "Samsunspor": "萨姆松体育",
    "Goztepe": "格兹特佩",
    "Kasimpasa SK": "卡森柏沙",
    "Eyüpspor": "埃于普体育",
    "Gazişehir Gaziantep": "加济安泰普",
    "Torku Konyaspor": "科尼亚体育",
    "Kocaelispor": "科贾埃利体育",
    "Akhisar Belediyespor": "阿克希萨尔",
    "Amed SK": "阿梅德",
    "Erzurum BB": "埃尔祖鲁姆",
    "Genclerbirligi SK": "根克勒比利吉",
    # 苏超
    "Celtic": "凯尔特人",
    "Rangers": "流浪者",
    "Hearts": "哈茨",
    "Hibernian": "希伯尼安",
    "Aberdeen": "阿伯丁",
    "Dundee United": "邓迪联",
    "Dundee FC": "邓迪",
    "Kilmarnock": "基尔马诺克",
    "Motherwell": "马瑟韦尔",
    "St Johnstone": "圣约翰斯通",
    "St Mirren": "圣米伦",
    "Falkirk F.C.": "福尔柯克",
    # 比甲
    "Anderlecht": "安德莱赫特",
    "Genk": "亨克",
    "Gent": "根特",
    "Standard Liege": "标准列日",
    "Charleroi": "沙勒罗瓦",
    "Cercle Brugge KSV": "色格拉布鲁日",
    "Leuven": "勒芬",
    "KV Mechelen": "梅赫伦",
    "Royal Antwerp": "安特卫普",
    "Union Saint-Gilloise": "圣吉罗斯",
    "SK Beveren": "贝弗伦",
    "SV Zulte-Waregem": "聚尔特瓦雷赫姆",
    "RAAL La Louvière": "拉卢维耶尔",
    "Lommel SK": "洛默尔",
    "Sint Truiden": "圣特赖登",
    "Westerlo": "韦斯特洛",
    # 巴甲
    "Flamengo": "弗拉门戈",
    "Palmeiras": "帕尔梅拉斯",
    "Corinthians": "科林蒂安",
    "Sao Paulo": "圣保罗",
    "Santos": "桑托斯",
    "Grêmio": "格雷米奥", "Gremio": "格雷米奥",
    "Internacional": "巴西国际",
    "Atletico Mineiro": "米内罗竞技",
    "Botafogo": "博塔弗戈",
    "Fluminense": "弗鲁米嫩塞",
    "Cruzeiro": "克鲁塞罗",
    "Vasco da Gama": "瓦斯科达伽马",
    "Bahia": "巴伊亚",
    "Coritiba": "科里蒂巴",
    "Atletico Paranaense": "巴拉纳竞技",
    "Bragantino-SP": "布拉甘蒂诺",
    "Mirassol": "米拉索尔",
    "Chapecoense": "沙佩科恩斯",
    "Remo": "雷莫",
    # 美职联
    "LA Galaxy": "洛杉矶银河",
    "Los Angeles FC": "洛杉矶FC",
    "Inter Miami CF": "迈阿密国际",
    "Atlanta United FC": "亚特兰大联",
    "Austin FC": "奥斯汀FC",
    "Charlotte FC": "夏洛特FC",
    "Chicago Fire": "芝加哥火焰",
    "FC Cincinnati": "辛辛那提FC",
    "Colorado Rapids": "科罗拉多急流",
    "Columbus Crew SC": "哥伦布机员",
    "D.C. United": "华盛顿特区联",
    "FC Dallas": "达拉斯FC",
    "Houston Dynamo": "休斯顿迪纳摩",
    "Minnesota United FC": "明尼苏达联",
    "Nashville SC": "纳什维尔",
    "New England Revolution": "新英格兰革命",
    "New York City FC": "纽约城",
    "New York Red Bulls": "纽约红牛",
    "Orlando City SC": "奥兰多城",
    "Philadelphia Union": "费城联合",
    "Portland Timbers": "波特兰伐木工",
    "Real Salt Lake": "皇家盐湖城",
    "San Jose Earthquakes": "圣何塞地震",
    "Seattle Sounders FC": "西雅图海湾人",
    "Sporting Kansas City": "堪萨斯城竞技",
    "St. Louis City SC": "圣路易斯城",
    "Toronto FC": "多伦多FC",
    "Vancouver Whitecaps FC": "温哥华白帽",
    "San Diego FC": "圣迭戈FC",
    "CF Montreal": "蒙特利尔CF",
    # 日职
    "Kawasaki Frontale": "川崎前锋",
    "FC Tokyo": "东京FC",
    "Cerezo Osaka": "大阪樱花",
    "Avispa Fukuoka": "福冈黄蜂",
    "Hiroshima Sanfrecce FC": "广岛三箭",
    "FC Machida Zelvia": "町田泽维亚",
    "Kyoto Purple Sanga": "京都不死鸟",
    "Shimizu S Pulse": "清水心跳",
    "Kashiwa Reysol": "柏太阳神",
    "Tokyo Verdy": "东京绿茵",
    "JEF United Chiba": "千叶市原",
    "Mito HollyHock": "水户蜀葵",
    "Fagiano Okayama": "冈山绿雉",
    "V-Varen Nagasaki": "长崎航海",
    "Nagoya Grampus": "名古屋鲸八",
    "Yokohama F. Marinos": "横滨水手",
    "Urawa Red Diamonds": "浦和红钻",
    "Kashima Antlers": "鹿岛鹿角",
    "Gamba Osaka": "大阪钢巴",
    # K联赛
    "Ulsan Hyundai FC": "蔚山现代",
    "Jeonbuk Hyundai Motors": "全北现代",
    "FC Seoul": "首尔FC",
    "Pohang Steelers": "浦项制铁",
    "Gwangju FC": "光州FC",
    "Daejeon Citizen": "大田市民",
    "Jeju United FC": "济州联",
    "Sangju Sangmu FC": "金泉尚武",
    "Bucheon FC 1995": "富川FC",
    "FC Anyang": "安养FC",
    # 欧冠/欧战
    "Red Star Belgrade": "贝尔格莱德红星",
    "Dinamo Zagreb": "萨格勒布迪纳摩",
    "Sparta Prague": "布拉格斯巴达",
    "ŠK Slovan Bratislava": "布拉迪斯拉发", "Slovan Bratislava": "布拉迪斯拉发",
    "SK Sturm Graz": "格拉茨风暴",
    "Bodø/Glimt": "博德闪耀", "Bodo/Glimt": "博德闪耀",
    "Olympiakos Piraeus": "奥林匹亚科斯",
    "FC Kairat": "凯拉特",
    "PFC Levski Sofia": "列夫斯基索菲亚",
    "Sabah FK": "萨巴赫",
    "AGF Aarhus": "奥胡斯",
    "FK Kauno Žalgiris": "扎尔吉里斯",
    "NK Celje": "采列",
    "FC Ararat-Armenia": "亚拉拉特",
    "Hapoel Be'er Sheva": "贝尔谢巴工人",
    "Mjällby AIF": "米亚尔比",
    # 其他
    "AS Monaco": "摩纳哥",
    "Frosinone Calcio": "弗罗西诺内",
    "AC Milan": "AC米兰",
    "TSG Hoffenheim": "霍芬海姆",
    "Club Brugge KV": "布鲁日",
    "Borussia M'gladbach": "门兴格拉德巴赫",
    "Bologna FC 1909": "博洛尼亚",
    "Sunderland AFC": "桑德兰",
    "Lille OSC": "里尔",
    "RC Lens": "朗斯",
    "Falkirk F.C.": "福尔柯克",
    "Leuven": "勒芬",
    "Hull City AFC": "赫尔城",
    "Vissel Kobe": "神户胜利船",
    "Vitoria": "吉马良斯",
    "Vitória SC": "吉马良斯",
    "Watford": "沃特福德",
    "West Bromwich Albion": "西布罗姆维奇",
    "Willem II": "威廉二世",
    "Wolverhampton Wanderers": "狼队",
    "Wrexham AFC": "雷克瑟姆",
    "Çaykur Rizespor": "里泽体育",
}


# 合并现有 index.html 中的映射（以防遗漏）
html = (ROOT / "index.html").read_text(encoding="utf-8")
m = re.search(r"const TEAM_NAMES = \{(.*?)\};", html, re.S)
if m:
    for k, v in re.findall(r"'([^']+)': '([^']+)'", m.group(1)):
        T.setdefault(k, v)

# 写出
out = {k: T[k] for k in sorted(T)}
(ROOT / "data" / "team_names.json").write_text(
    json.dumps(out, ensure_ascii=False, separators=(",", ":")), encoding="utf-8")
print(f"team_names.json: {len(out)} 条映射")
